automation:
  alias: deadman_reset
  trigger: 
    platform: time_pattern
    # You can also match on interval. This will match every 3 minutes
    minutes: "/3"
  action:
    service: rest_command.reset_deadman
    data:
      token: !secret pushbullet_key
      delay: 600

rest_command:
   reset_deadman:
      url: "https://deadman.illuminum.de/reset.php?delay={{delay}}&token={{token}}"
